server:
  servlet:
    context-path: /

  port: 8881

spring:

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # 配置数据库连接信息
  datasource:
#    url: jdbc:mysql://sh-cdb-75vlqi3r.sql.tencentcdb.com:63169/device_status_db_test?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: "root1234"
#    driver-class-name: com.mysql.cj.jdbc.Driver

#    local server configuration
    url: jdbc:sqlserver://139.198.19.162:1433;DatabaseName=device_status_db
#    url: jdbc:sqlserver://localhost:1433;DatabaseName=device_status_db?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: "sa"
    password: "Bjpv2017"

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    database: sql_server
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.configuration.ImprovedNamingStrategy

    database-platform: org.hibernate.dialect.SQLServer2008Dialect



  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false

